version: '3.8'

services:
  empreendimentos-api:
    build: .
    container_name: empreendimentos-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    tty: true
